# Generated by Django 4.1.7 on 2023-11-19 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.date(2023, 11, 19)),
        ),
    ]
