# Generated by Django 4.1.7 on 2023-11-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrep', '0004_remove_user_date_joined_remove_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('client', 'client')], default='client', max_length=10),
        ),
    ]
