# Generated by Django 4.1.7 on 2023-11-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livrep', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
